name: bnkproject
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2


  flame: ^1.15.0
  provider: ^6.1.5+1

  # ✅ video guide
  video_player: ^2.9.1

  # network & utils
  http: ^1.6.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3

  # camera & face
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_commons: ^0.9.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/game/
    - assets/icon/
    # 필요하면 이미지도 여기에 추가
    # - assets/images/face_guide.png

flutter_launcher_icons:
  android: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png

