name: bnkproject
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # ✅ keep aligned with your current lockfile/install (17.x)
  flutter_local_notifications: ^17.2.4

  # webview
  webview_flutter: ^4.7.0

  flame: ^1.18.0
  provider: ^6.1.5+1

  # ✅ video guide
  video_player: ^2.9.1

  # network & utils
  http: ^1.6.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.3

  # camera & face_legacy
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_selfie_segmentation: ^0.10.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/game/
    - assets/icon/
    - assets/images/goals/
    - assets/images/places/
    - assets/images/sto/
    - assets/images/game/card/
    - assets/images/game/dodge/
    # 필요하면 이미지도 여기에 추가
    # - assets/images/face_guide.png
    - assets/chart/lw.html
    - assets/chart/lightweight-charts.js

flutter_launcher_icons:
  android: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/app_icon.png
